name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      # 1️⃣ 取得 repo 內容
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 安裝 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ 安裝依賴套件（如果有 requirements.txt）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt pip install -r requirements.txt
          pip install pyinstaller

      # 4️⃣ 建立 EXE
      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole app.py

      # 5️⃣ 上傳 EXE artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: dist/app.exe