name: Build macOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller streamlit pandas plotly

    - name: Build app
      run: pyinstaller --onefile app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: dist/app