name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build macOS Application (.app bundle)
        run: |
          pip install pyinstaller
          # 使用 --onedir 和 --windowed 參數來建立一個標準的 .app 應用程式包
          # 如果 app.py 是一個 GUI 程式 (例如 Tkinter/PyQt)，應使用 --windowed
          # dist/app.app 將是一個完整的應用程式資料夾
          pyinstaller --onedir --windowed app.py

      - name: Rename and Upload Artifact (.app)
        uses: actions/upload-artifact@v4
        with:
          # 將路徑指向 PyInstaller 建立的 .app 應用程式目錄
          name: macos-app-bundle
          path: dist/app.app
